# Generated by Django 4.1.5 on 2023-01-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
